topics:
  - Addressing
  - Census
  - Consumer Finance
  - Disasters
  - Discovery
  - Economic Development
  - Education
  - Employment
  - Entrepreneurship & Small Businesses
  - Environment
  - Federal Funding
  - Health
  - Housing
  - Opioids
  - Refugees
  - Rural
  - Transportation
  - Veterans
years:
  - 2016
  - 2017
  - 2018
  - 2019
  - 2020
  - 2021
  - 2022
  - 2023
  - 2024
agencies:
  - label: Census Bureau
  - label: City of Coral Gables
  - label: Consumer Financial Protection Bureau
  - label: Environmental Protection Agency
  - label: Department of Agriculture
  - label: Department of Commerce
  - label: Department of Education
  - label: Department of Energy
  - label: Department of Health and Human Services
  - label: Department of Homeland Security
  - label: Department of Housing and Urban Development
  - label: Department of Labor
  - label: Department of State
  - label: Department of the Treasury
  - label: Department of Transportation
  - label: Department of Veterans Affairs
  - label: Economic Development Administration
  - label: Federal Emergency Management Agency
  - label: Food and Drug Administration
  - label: Forest Service
  - label: Harvard Business School
  - label: Instituto del Desarrollo de la Juventud
  - label: Minority Business Development Agency
  - label: National Institute of Biomedical Imaging and Bioengineering
  - label: National Institutes of Health
  - label: National League of Cities
  - label: National Oceanic and Atmospheric Administration
  - label: National Renewable Energy Laboratory
  - label: National Urban Indian Family Coalition
  - label: Natives Count Coalition
  - label: New York City Mayor's Office of the Chief Technology Officer
  - label: Office of Management and Budget
  - label: Office of the U.S. Surgeon General
  - label: Puerto Rico Department of Economic Development and Commerce
  - label: Puerto Rico Negociado de Energía
  - label: Puerto Rico Office of Management and Budget
  - label: The Wilson Center
  - label: USA for UNHCR
    value: USA for United Nations High Commissioner for Refugees
  - label: White House Council of Economic Advisors
  - label: White House Office of Science and Technology Policy
